
/// Flutter icons SRLIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SRLIcons
///      fonts:
///       - asset: fonts/SRLIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SRLIcons {
  SRLIcons._();

  static const _kFontFam = 'SRLIcons';
  static const _kFontPkg = null;

  static const IconData center_map = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forecast_alt = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forecast = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layers = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locations_filled = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locations = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radar = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
